language: r

r:
  - oldrel
  - release

os:
  - linux
  - osx

cache:
  packages: true

r_packages:
  devtools

addons:
  apt:
    packages:
    - libv8-dev

after_success:
  - R -e 'devtools::load_all(); testthat::test_dir("tests/testthat")'