language: r

r:
  - oldrel
  - release

os:
  - linux
  - osx

cache:
  packages: true
  directories:
    - travis_phantomjs

install:
  - R -e 'install.packages(c("devtools", "shinytest"))'
  - R -e 'devtools::install_deps(dep = T)'
  - R -e 'shinytest::installDependencies()'

addons:
  apt:
    packages:
    - libv8-dev

after_success:
  - R -e 'devtools::load_all(); testthat::test_dir("tests/testthat")'